### ISSUE TITLE
Add support for defining YAML Data Flows

### ISSUE THREAD

**Issue by ivansabik** [ivansabik/panditas#15]
# Example

```yaml
name: Agency Experience
steps:
- type: DataSet
  name: claims
  params:
    columns:
    - revisionId
    - lossReserveBalance
    - claimStatus
    df_path: claims.csv
    source: csv
- type: DataSet
  name: inforce
  params:
    columns:
    - revisionId
    - policyId
    - policyInforcePremium
    df_path: inforce.csv
    source: csv
- type: DataSet
  name: transactions
  params:
    columns:
    - revisionId
    - policyId
    - policyChangeTransactionType
    - policyChangeWrittenPremium
    df_path: transactions.csv
    source: csv
- type: DataSet
  name: policies
  params:
    columns:
    - policyId
    - policyNumber
    df_path: policies.csv
    source: csv
- type: DataSet
  name: agencies
  params:
    columns:
    - revisionId
    - agencyName
    df_path: agencies.csv
    source: csv
- type: DataSet
  name: lines
  params:
    columns:
    - revisionId
    - lineOfBusinessName
    df_path: lines.csv
    source: csv
- type: MergeMultipleRule
  name: merge_facts_dims
  params:
    data_sets:
    - claims
    - inforce
    - transactions
    - policies
    - agencies
    - lines
    merge_types:
    - outer
    - outer
    - outer
    - left
    - left
- type: ConstantColumn
  name: add_claim_count_column
  params:
    column_name: claimCount
    column_value: 0
- type: ConditionalFill
  name: calculate_claim_count
  params:
    fill_column: claimCount
    fill_value: 1
    where_column: claimStatus
    where_condition: contains
    where_condition_values:
    - Open
- type: ConstantColumn
  name: add_new_count_column
  params:
    column_name: newCount
    column_value: 0
- type: ConditionalFill
  name: calculate_new_count
  params:
    fill_column: newCount
    fill_value: 1
    where_column: policyChangeTransactionType
    where_condition: ==
    where_condition_values:
    - New
- type: ConstantColumn
  name: add_new_premium
  params:
    column_name: newPremium
    column_value: 0
- type: ConditionalFill
  name: calculate_new_premium
  params:
    fill_column: newPremium
    fill_value: 1
    where_column: policyChangeTransactionType
    where_condition: ==
    where_condition_values:
    - New
- type: ConstantColumn
  name: add_cancel_count_column
  params:
    column_name: cancelCount
    name: add_cancel_count_column
- type: ConditionalFill
  name: calculate_cancel_count
  params:
    fill_column: cancelCount
    fill_value: 1
    where_column: policyChangeTransactionType
    where_condition: ==
    where_condition_values:
    - Canceled
- type: ConstantColumn
  name: add_cancel_premium
  params:
    column_name: cancelPremium
    column_value: 0
- type: ConditionalFill
  name: calculate_cancel_premium
  params:
    fill_column: cancelPremium
    fill_value: 1
    where_column: policyChangeTransactionType
    where_condition: ==
    where_condition_values:
    - Canceled
- type: PivotTable
  name: group_by_agency_line
  params:
    group_columns:
    - agencyName
    - lineOfBusinessName
    group_values:
    - claimCount
    - lossReserveBalance
    - newCount
    - newPremium
    - cancelCount
    - cancelPremium
    - policyInforcePremium
    group_functions:
    - sum
    - last
    - sum
    - sum
    - sum
    - sum
    - max
```
